name: CI

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analyse the code with black
      run: |
        black $(git ls-files '*.py') --check

    - name: Analyse the code with flake8
      run: |
        flake8 $(git ls-files '*.py')

    - name: Test the API with pytest
      run: |
        pytest src/api/tests

    - name: Test the pipeline with pytest
      run: |
        pytest src/pipeline/stages/tests