name: CI

on: [push, pull_request]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: black format
      run: |
        python -m black $(git ls-files '*.py') --check

    - name: flake8 linter
      uses: py-actions/flake8@v2
      with:
        max-line-length: "120"
        exclude: "__init__.py"
        ignore: |
          "E501"
          "E722"
          "W503"

    - name: pytest api
      run: |
        python -m pytest src/api/tests

    - name: pytest pipeline
      run: |
        python -m pytest src/pipeline/stages/tests